// apps/@examples/tour-custom/src/pages/_app.tsx
import { DoptProvider } from '@dopt/react';
import { useIdentifyUser } from '@dopt/react-users';

import { useMemo } from 'react';
import { nanoid } from 'nanoid';

import { Home } from '@/pages';
import './_app.css';

export function App() {
  /**
   * Create a static example user.
   */
  const user = useMemo(
    () => ({
      identifier: nanoid(),
      properties: {
        company: 'Dopt',
        role: 'admin',
        inTrial: true,
      },
    }),
    []
  );

  /**
   * Identify the example user to Dopt the first time the App loads.
   */
  const userId = useIdentifyUser(user);

  return (
    <DoptProvider
      apiKey={import.meta.env.VITE_DOPT_BLOCKS_API_KEY}
      userId={userId}
      flowVersions={{ 'custom-tour-component': 1 }}
    >
      <Home />
    </DoptProvider>
  );
}

// apps/@examples/tour-custom-vue/src/pages/App.vue
<script setup lang="ts">
import { Dopt } from '@dopt/javascript';
import { DoptApiClient as UsersApiClient } from '@dopt/users-javascript-browser-client';

import { provide, ref, readonly } from 'vue';
import { nanoid } from 'nanoid';

import HomePage from './HomePage.vue';

const dopt = new Dopt({
  apiKey: import.meta.env.VITE_DOPT_BLOCKS_API_KEY,
  flowVersions: { 'custom-tour-component': 1 },
  userId: undefined,
});

/**
 * Create a provider for dopt for all children.
 */
provide('dopt', readonly(dopt));

(async function () {
  /**
   * Create a static example user.
   */
  const user = {
    identifier: nanoid(),
    properties: {
      company: 'Dopt',
      role: 'admin',
      inTrial: true,
    },
  };

  const usersClient = new UsersApiClient({
    environment: import.meta.env.VITE_DOPT_USERS_SDK_BASE_URL,
    apiKey: import.meta.env.VITE_DOPT_USERS_API_KEY,
  });

  /**
   * Identify the example user to Dopt during App setup.
   */
  await usersClient.users.identifyUser(user);

  dopt.configure({ userId: user.identifier });
})();
</script>

<template>
  <template v-if="dopt">
    <HomePage />
  </template>
</template>

<style>
* {
  box-sizing: border-box;
}

:root {
  font-family: -apple-system, BlinkMacSystemFont, avenir next, avenir, segoe ui,
    helvetica neue, helvetica, Cantarell, Ubuntu, roboto, noto, arial,
    sans-serif;
  line-height: 1.5;
}
</style>
